steps:
  build:
    image: maven:3.8.1-openjdk-17
    commands:
      - echo "start run the build step "
      - echo $${WOODPECKER_NOTIFY_DISCORD_ID}
      - echo $${WOODPECKER_NOTIFY_DISCORD_TOKEN}
    secrets: [WOODPECKER_NOTIFY_DISCORD_ID, WOODPECKER_NOTIFY_DISCORD_TOKEN]

    when:
      event: pull_request
  compile:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - echo "compile finish"
    when:
      event: pull_request

  spotbugs:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - mvn spotbugs:check -Dspotbugs.excludeFilterFile=./findbugs-exclude.xml #exclude bug list
    when:
      event: pull_request

  pmd:
    image: maven:3.8.1-openjdk-17
    commands:
      - mvn clean
      - mvn compile
      - mvn pmd:pmd
    when:
      event: pull_request

#  test:
#    image: maven:3.8.1-openjdk-17
#    commands:
#      - mvn test

# 設定通知，discord 作為通知工具
  notify:
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: woodpecker_notify_discord_id
      webhook_token: 
        from_secret: woodpecker_notify_discord_token
      avatar_url: https://woodpecker-ci.org/img/logo.svg
      link_names: true
      template: >
    when:
      event:
        - pull_request
      status:
        - failure
        - success
